# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('year', models.CharField(blank=True, choices=[('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016')], max_length=4, verbose_name='Year')),
                ('info', models.TextField(blank=True, default='', verbose_name='Info')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'verbose_name': 'Project',
            },
        ),
    ]
