# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JZ', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('info', models.TextField(blank=True, default='', verbose_name='Info')),
            ],
            options={
                'verbose_name_plural': 'About',
                'verbose_name': 'About',
            },
        ),
    ]
