# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JZ', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
